//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.30 at 06:46:14 PM PDT 
//


package com.polaris.fulfillment.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FulFillment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FulFillment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FulFillmentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FulFillmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FulFillmentBalance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="FulFillmentStatus" type="{http://webservices.fulfillment.polaris.com}EnumFulFillmentStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FulFillment", propOrder = {
    "fulFillmentNumber",
    "fulFillmentName",
    "fulFillmentBalance",
    "fulFillmentStatus"
})
public class FulFillment {

    @XmlElement(name = "FulFillmentNumber", required = true)
    protected String fulFillmentNumber;
    @XmlElement(name = "FulFillmentName", required = true)
    protected String fulFillmentName;
    @XmlElement(name = "FulFillmentBalance")
    protected double fulFillmentBalance;
    @XmlElement(name = "FulFillmentStatus", required = true)
    protected EnumFulFillmentStatus fulFillmentStatus;

    /**
     * Gets the value of the fulFillmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulFillmentNumber() {
        return fulFillmentNumber;
    }

    /**
     * Sets the value of the fulFillmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulFillmentNumber(String value) {
        this.fulFillmentNumber = value;
    }

    /**
     * Gets the value of the fulFillmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulFillmentName() {
        return fulFillmentName;
    }

    /**
     * Sets the value of the fulFillmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulFillmentName(String value) {
        this.fulFillmentName = value;
    }

    /**
     * Gets the value of the fulFillmentBalance property.
     * 
     */
    public double getFulFillmentBalance() {
        return fulFillmentBalance;
    }

    /**
     * Sets the value of the fulFillmentBalance property.
     * 
     */
    public void setFulFillmentBalance(double value) {
        this.fulFillmentBalance = value;
    }

    /**
     * Gets the value of the fulFillmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EnumFulFillmentStatus }
     *     
     */
    public EnumFulFillmentStatus getFulFillmentStatus() {
        return fulFillmentStatus;
    }

    /**
     * Sets the value of the fulFillmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumFulFillmentStatus }
     *     
     */
    public void setFulFillmentStatus(EnumFulFillmentStatus value) {
        this.fulFillmentStatus = value;
    }

}
